// @ts-ignore
/* eslint-disable */
// Code generated by protoc-gen-ts-umi. DO NOT EDIT.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.

declare namespace NewsV1 {
	/** MessageListOption */
	type MessageListOption = {
		name?:string
	}
	/** MessageGetOption */
	type MessageGetOption = {
		id?:number
	}
	/** MessageUpdateOption */
	type MessageUpdateOption = {
		name?:string
	}
	/** MessageCreateOption */
	type MessageCreateOption = {
		name?:string
	}
	/** MessageDeleteOption */
	type MessageDeleteOption = {
		id?:number
	}
	/** MessageList */
	type MessageList = {
		message?:string
	}
	/** Message */
	type Message = {
	}
}

