// @ts-ignore
/* eslint-disable */
// Code generated by protoc-gen-ts-umi. DO NOT EDIT.
import { request } from 'umi';

const APIService = '/api';
// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.

type Options = {
  [key: string]: any;
};

/** List  查看发送队列 /api */
export async function List(params: NewsV1.NoticeListOption, options?: Options) {
  return request<NewsV1.NoticeList>(APIService + '/users/notice', {
    method: 'GET',
    params: { ...params },
    ...(options || {}),
  });
}

/** Send  发送一个通知 /api */
export async function Send(params: NewsV1.NoticeCreateOption, options?: Options) {
  return request<NewsV1.Notice>(APIService + '/users/notice', {
    method: 'POST',
    params: { ...params },
    ...(options || {}),
  });
}
