// @ts-ignore
/* eslint-disable */
// Code generated by protoc-gen-ts-umi. DO NOT EDIT.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.

declare namespace SystemsV1 {
	/** FileCreateOption */
	type FileCreateOption = {
		name?:string
	}
	/** FileDeleteOption */
	type FileDeleteOption = {
		id?:string
	}
	/** FileList */
	type FileList = {
		message?:string
	}
	/** File */
	type File = {
	}
	/** FileListOption */
	type FileListOption = {
		name?:string
	}
	/** FileGetOption */
	type FileGetOption = {
		id?:string
	}
	/** FileUpdateOption */
	type FileUpdateOption = {
		name?:string
	}
}

